#!/bin/bash

# test-integer 3: evaluate whether the value exists within a range

MIN_VAL=1
MAX_VAL=100

INT=50

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if [[ INT -ge MIN_VAL && INT -le MAX_VAL ]]; then
		echo "$INT is with $MIN_VAL and $MAX_VAL"
	else
		echo "$INT is out of range."
	fi
else
	echo "INT is not an integer." >&2
	exit 1
fi
